# 项目设置
novel:
  # 跨域设置
  cors:
    # 允许跨域url
    allow-origins:
      - http://localhost:1024
      - http://localhost:8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/novel?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: test123456

  data:
    # Redis 配置
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456

  elasticsearch:
    uris:
      - https://my-deployment-ce7ca3.es.us-central1.gcp.cloud.es.io:9243
    username: elastic
    password: qTjgYVKSuExX
